name: hpfuapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^2.0.2
  dio: ^3.0.7
  fluro: ^2.0.3
  shared_preferences: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pull_to_refresh: ^2.0.0
  connectivity: ^0.4.4
  path_provider: ^2.0.0
  event_bus: ^1.1.0
  synchronized: '>=2.0.2 <4.0.0'
  qr_flutter: ^3.0.0
  permission_handler: ^4.0.0
  open_file: ^2.1.1
  flutter_downloader: ^1.6.0
  flutter_datetime_picker: ^1.5.0
  flutter_picker: ^2.0.1
  flutter_xupdate: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_easyloading: ^3.0.0
  launch_review: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/ic_login_button_enabled.png
    - images/ic_login_button_disabled.png
    - images/ic_back_white.png
    - images/ic_no_data_view.png
    - images/ic_splash_logo.png
    - images/ic_home_caigoujiju.png
    - images/ic_home_money.png
    - images/ic_home_shanghu.png
    - images/ic_home_tixian.png
    - images/ic_home_jiju.png
    - images/ic_home_hehuoren.png
    - images/ic_home_dingdan.png
    - images/ic_home_bg.png
    - images/ic_home_caigoujiju.png
    - images/ic_home_chaxun.png
    - images/ic_home_dizhi.png
    - images/ic_home_duihuan.png
    - images/ic_home_fenhong.png
    - images/ic_home_renzheng.png
    - images/ic_home_shouyi.png
    - images/ic_home_v.png
    - images/ic_home_xiaoxi.png
    - images/ic_home_paihangbang.png
    - images/ic_home_arrow_white.png
    - images/ic_mine_arrow.png
    - images/ic_home_my.png
    - images/ic_home_my_check.png
    - images/ic_home_shouye.png
    - images/ic_home_shouye_check.png
    - images/ic_home_yaoqing.png
    - images/ic_home_yaoqing_check.png
    - images/ic_home_yeji.png
    - images/ic_home_yeji_check.png
    - images/ic_invite_bg.png
    - images/ic_invite_erweima.png
    - images/ic_yeji_bg.png
    - images/ic_me_daichuli.png
    - images/ic_me_shouyizonglian.png
    - images/ic_mine_forme.png
    - images/ic_mine_shezhi.png
    - images/ic_mine_tuichu.png
    - images/ic_invite_card.png
    - images/ic_invite_left.png
    - images/ic_invite_pengyouquan.png
    - images/ic_invite_right.png
    - images/ic_invite_weixin.png
    - images/ic_invite_xiazai.png
    - images/ic_mine_touxiang.png
    - images/ic_mine_bianxing.png
    - images/ic_mine_me_bg.png
    - images/ic_mine_tuoyuan.png
    - images/ic_mine_v.png
    - images/ic_mine_heiv.png
    - images/ic_back_black.png
    - images/ic_shop_search.png
    - images/ic_launcher.png
    - images/ic_withdraw_bg.png
    - images/ic_arrow_down.png
    - images/ic_trade_arrow_down.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
